/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;

import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author chuan
 */
public class RuleDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form ScoreBoradDialog
     */
    public RuleDialog(int tab) {
        //super(parent, modal);
        initComponents();
        jTabbedPane1.setSelectedIndex(tab);
        System.out.println(tab+" == "+jTabbedPane1.getSelectedIndex());
        
        playAgainB.setVisible(false);
        String str = "Rule 1:<br/><br/><br/><br/>Rule 2:<br/><br/><br/><br/>Rule 3:<br/><br/><br/>P.S. <br/><br/><br/><br/>";
        //str = "Rule 1:<br/><br/>Rule 2:<br/><br/>Rule 3:";
        ruleTitleLabel.setText("<html>" + str + "</html>");
        //str="";
        str = "Each turn, the car can accelerate, decelerate or maintain the same speed at the horizontal and/or vertical direction.<br/><br/>";
        str += "The new position and the move line segments of car must entirely lie on the pathway of track, otherwise they crash.<br/><br/>";
        str += "The car which reaches the finish line first wins the race.<br/><br/>";
        str += "There will be at most seven checkpoint lines, and the car needs to cross the checkpoint lines in the particular order as following - red, orange, yellow, green, blue, indigo, and violet.";
        ruleLabel.setText("<html>" + str + "</html>");

        str = "1. There must be one start point, one finish line, and at least one checkpoint line.<br/><br/>";
        str += "2. All points and lines should be reasonable. There must be part of them on the pathway instead of entirely on the barriers. ";
        str += "Also, there are some symbols to indicate whether it is reasonable. Green check represents legal; red cross means illegal.<br/><br/>";
        str += "3. After point and lines are all legal, then press the draw button to draw a path from start point, cross the checkpoint line in order, and reach finish line. ";
        str += "If any of  drawing line doesn't hit the barriers, then drawing part is done and green check will show up.<br/><br/>";
        str += "4. While every button with green check, finish button is enable. After clicking on it, user needs to give this track an unique name among all customised tracks.";
        designLabel.setText("<html>" + str + "</html>");
        System.out.println("RuleDialog");
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                //parent.dispose();
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        gamePanel = new javax.swing.JPanel();
        ruleLabel = new javax.swing.JLabel();
        ruleTitleLabel = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        keyContorlPanel = new javax.swing.JPanel();
        keyDirectionContorlPanel = new javax.swing.JPanel();
        keyControlLabel0 = new javax.swing.JLabel();
        keyControlLabel1 = new javax.swing.JLabel();
        keyControlLabel2 = new javax.swing.JLabel();
        keyControlLabel3 = new javax.swing.JLabel();
        keyControlLabel4 = new javax.swing.JLabel();
        keyControlLabel5 = new javax.swing.JLabel();
        keyControlLabel6 = new javax.swing.JLabel();
        keyControlLabel7 = new javax.swing.JLabel();
        keyControlLabel8 = new javax.swing.JLabel();
        comfirmKeyPanel = new javax.swing.JPanel();
        comfirmKeyLabel = new javax.swing.JLabel();
        buttonContorlPanel = new javax.swing.JPanel();
        comfirmButtonPanel = new javax.swing.JPanel();
        comfirmButtonLabel = new javax.swing.JLabel();
        buttonDirectionContorlPanel = new javax.swing.JPanel();
        buttonControlLabel0 = new javax.swing.JLabel();
        buttonControlLabel1 = new javax.swing.JLabel();
        buttonControlLabel2 = new javax.swing.JLabel();
        buttonControlLabel3 = new javax.swing.JLabel();
        buttonControlLabel4 = new javax.swing.JLabel();
        buttonControlLabel5 = new javax.swing.JLabel();
        buttonControlLabel6 = new javax.swing.JLabel();
        buttonControlLabel7 = new javax.swing.JLabel();
        buttonControlLabel8 = new javax.swing.JLabel();
        designPanel = new javax.swing.JPanel();
        designLabel = new javax.swing.JLabel();
        playAgainB = new javax.swing.JButton();

        setTitle("Rule");
        setPreferredSize(new java.awt.Dimension(500, 350));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        ruleTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePanelLayout.createSequentialGroup()
                .addComponent(ruleTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ruleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ruleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ruleTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Game", gamePanel);

        keyContorlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Key Control", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times", 1, 14))); // NOI18N

        keyDirectionContorlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direction", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times", 1, 14))); // NOI18N
        keyDirectionContorlPanel.setLayout(new java.awt.GridLayout(3, 3));

        keyControlLabel0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keyControlLabel0.setText("Q");
        keyDirectionContorlPanel.add(keyControlLabel0);

        keyControlLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keyControlLabel1.setText("W");
        keyDirectionContorlPanel.add(keyControlLabel1);

        keyControlLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keyControlLabel2.setText("E");
        keyDirectionContorlPanel.add(keyControlLabel2);

        keyControlLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keyControlLabel3.setText("A");
        keyDirectionContorlPanel.add(keyControlLabel3);

        keyControlLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keyControlLabel4.setText("S");
        keyDirectionContorlPanel.add(keyControlLabel4);

        keyControlLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keyControlLabel5.setText("D");
        keyDirectionContorlPanel.add(keyControlLabel5);

        keyControlLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keyControlLabel6.setText("Z");
        keyDirectionContorlPanel.add(keyControlLabel6);

        keyControlLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keyControlLabel7.setText("X");
        keyDirectionContorlPanel.add(keyControlLabel7);

        keyControlLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keyControlLabel8.setText("C");
        keyDirectionContorlPanel.add(keyControlLabel8);

        comfirmKeyPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Comfirm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times", 1, 14))); // NOI18N
        comfirmKeyPanel.setLayout(new java.awt.GridLayout(1, 0));

        comfirmKeyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comfirmKeyLabel.setText("Space / Enter");
        comfirmKeyPanel.add(comfirmKeyLabel);

        javax.swing.GroupLayout keyContorlPanelLayout = new javax.swing.GroupLayout(keyContorlPanel);
        keyContorlPanel.setLayout(keyContorlPanelLayout);
        keyContorlPanelLayout.setHorizontalGroup(
            keyContorlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keyContorlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(keyContorlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comfirmKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keyContorlPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(keyDirectionContorlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        keyContorlPanelLayout.setVerticalGroup(
            keyContorlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keyContorlPanelLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(keyDirectionContorlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comfirmKeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        buttonContorlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Button Control", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times", 1, 14))); // NOI18N

        comfirmButtonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Comfirm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times", 1, 14))); // NOI18N
        comfirmButtonPanel.setLayout(new java.awt.GridLayout(1, 0));

        comfirmButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comfirmButtonLabel.setText("Move");
        comfirmButtonPanel.add(comfirmButtonLabel);

        buttonDirectionContorlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direction", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times", 1, 14))); // NOI18N
        buttonDirectionContorlPanel.setLayout(new java.awt.GridLayout(3, 3));

        buttonControlLabel0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonControlLabel0.setText("↖");
        buttonDirectionContorlPanel.add(buttonControlLabel0);

        buttonControlLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonControlLabel1.setText("↑");
        buttonDirectionContorlPanel.add(buttonControlLabel1);

        buttonControlLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonControlLabel2.setText("↗");
        buttonDirectionContorlPanel.add(buttonControlLabel2);

        buttonControlLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonControlLabel3.setText("←");
        buttonDirectionContorlPanel.add(buttonControlLabel3);

        buttonControlLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonControlLabel4.setText("x");
        buttonDirectionContorlPanel.add(buttonControlLabel4);

        buttonControlLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonControlLabel5.setText("→");
        buttonDirectionContorlPanel.add(buttonControlLabel5);

        buttonControlLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonControlLabel6.setText("↙");
        buttonDirectionContorlPanel.add(buttonControlLabel6);

        buttonControlLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonControlLabel7.setText("↓");
        buttonDirectionContorlPanel.add(buttonControlLabel7);

        buttonControlLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonControlLabel8.setText("↘");
        buttonDirectionContorlPanel.add(buttonControlLabel8);

        javax.swing.GroupLayout buttonContorlPanelLayout = new javax.swing.GroupLayout(buttonContorlPanel);
        buttonContorlPanel.setLayout(buttonContorlPanelLayout);
        buttonContorlPanelLayout.setHorizontalGroup(
            buttonContorlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonContorlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comfirmButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonContorlPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonDirectionContorlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        buttonContorlPanelLayout.setVerticalGroup(
            buttonContorlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonContorlPanelLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(buttonDirectionContorlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comfirmButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(keyContorlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(152, 152, 152)
                .addComponent(buttonContorlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonContorlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keyContorlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Control", controlPanel);

        javax.swing.GroupLayout designPanelLayout = new javax.swing.GroupLayout(designPanel);
        designPanel.setLayout(designPanelLayout);
        designPanelLayout.setHorizontalGroup(
            designPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, designPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(designLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
        );
        designPanelLayout.setVerticalGroup(
            designPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, designPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(designLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Design", designPanel);

        playAgainB.setText("OK");
        playAgainB.setPreferredSize(new java.awt.Dimension(200, 30));
        playAgainB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playAgainBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addComponent(playAgainB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(playAgainB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1))
        );

        getRootPane().setDefaultButton(playAgainB);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void playAgainBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playAgainBMouseClicked
        // TODO add your handling code here:
        //dispose();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_playAgainBMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        //dispose();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonContorlPanel;
    private javax.swing.JLabel buttonControlLabel0;
    private javax.swing.JLabel buttonControlLabel1;
    private javax.swing.JLabel buttonControlLabel2;
    private javax.swing.JLabel buttonControlLabel3;
    private javax.swing.JLabel buttonControlLabel4;
    private javax.swing.JLabel buttonControlLabel5;
    private javax.swing.JLabel buttonControlLabel6;
    private javax.swing.JLabel buttonControlLabel7;
    private javax.swing.JLabel buttonControlLabel8;
    private javax.swing.JPanel buttonDirectionContorlPanel;
    private javax.swing.JLabel comfirmButtonLabel;
    private javax.swing.JPanel comfirmButtonPanel;
    private javax.swing.JLabel comfirmKeyLabel;
    private javax.swing.JPanel comfirmKeyPanel;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel designLabel;
    private javax.swing.JPanel designPanel;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel keyContorlPanel;
    private javax.swing.JLabel keyControlLabel0;
    private javax.swing.JLabel keyControlLabel1;
    private javax.swing.JLabel keyControlLabel2;
    private javax.swing.JLabel keyControlLabel3;
    private javax.swing.JLabel keyControlLabel4;
    private javax.swing.JLabel keyControlLabel5;
    private javax.swing.JLabel keyControlLabel6;
    private javax.swing.JLabel keyControlLabel7;
    private javax.swing.JLabel keyControlLabel8;
    private javax.swing.JPanel keyDirectionContorlPanel;
    private javax.swing.JButton playAgainB;
    private javax.swing.JLabel ruleLabel;
    private javax.swing.JLabel ruleTitleLabel;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;

}
